"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type LanguageType = "id" | "en";

export const UI_TRANSLATIONS = {
  id: {
    appName: "Al-Qur'an Al-Kareem",
    appSub: "Quran Viewer & Murottal",
    surahList: "Daftar Surah",
    searchPlaceholder: "Cari nama surah, arti, atau nomor (misal: 36, Al-Waqi'ah, Kiamat)...",
    clear: "Hapus",
    tryAgain: "Coba Lagi",
    failedLoad: "Gagal memuat daftar Surah. Silakan coba beberapa saat lagi.",
    notFound: "Surah tidak ditemukan",
    notFoundSub: "Coba cari dengan kata kunci lain atau periksa ejaan Anda.",
    ayat: "Ayat",
    meccan: "Makkiyah",
    medinan: "Madaniyah",
    settingsTitle: "Pengaturan Membaca",
    settingsClose: "Tutup",
    translation: "Terjemahan",
    reciter: "Qori / Murottal",
    fontSize: "Ukuran Font",
    fontArabic: "Arab",
    fontTranslation: "Terjemahan",
    autoScroll: "Auto-Scroll Murottal",
    extras: "Fitur Tambahan",
    backToSurahs: "Kembali ke Daftar Surah",
    prevSurah: "Surah Sebelumnya",
    nextSurah: "Surah Selanjutnya",
    loadingDetails: "Gagal memuat detail surah. Periksa koneksi internet Anda.",
    invalidSurah: "Nomor surah tidak valid.",
    errorTitle: "Terjadi Kesalahan",
    backToHome: "Kembali ke Beranda",
    murottal: "Murottal",
    ayahOf: "Ayat ke-{current} dari {total}",
    playAyah: "Putar Audio Ayat",
    copyAyah: "Salin Ayat & Terjemahan",
    copied: "Tersalin!",
    speed: "Kecepatan Putar",
    mute: "Bisukan",
    unmute: "Bunyikan",
    themeLight: "Tema Terang",
    themeSepia: "Tema Sepia",
    themeDark: "Tema Gelap",
    copyright: "© {year} Al-Qur'an Al-Kareem. Powered by Next.js & alquran.cloud.",
    sumberApi: "Sumber API",
    readListenTadabbur: "BACA • DENGAR • TADABBUR",
    playSurah: "Putar Surah",
    pauseSurah: "Jeda Surah",
    readingMode: "Mode Baca",
    language: "Bahasa Aplikasi",
    floatingSettings: "Buka Pengaturan",
    prevAyah: "Ayat Sebelumnya",
    nextAyah: "Ayat Selanjutnya",
    repeatNone: "Tidak Mengulang",
    repeatAyah: "Ulangi Ayat",
    repeatSurah: "Ulangi Surah",
    heroTitle: "Temukan Kedamaian Dalam Membaca Al-Qur'an",
    heroSubtitle: "Aplikasi mushaf Al-Qur'an modern yang dilengkapi dengan terjemahan multibahasa, audio murottal interaktif, dan auto-scroll untuk kemudahan tadarus Anda.",
    showLatin: "Tampilkan Latin",
    highlightTajweed: "Highlight Tajwid",
    showIsyarat: "Tampilkan Isyarat",
    theme: "Tema Tampilan",
    themeCycle: "Ganti Tema",
    lastRead: "Terakhir Dibaca",
    bookmarksTitle: "Bookmark Saya",
    tahfidzHelper: "Fitur Tahfidz & Ulang",
    loopRange: "Ulang Rentang Ayat",
    startAyah: "Ayat Mulai",
    endAyah: "Ayat Selesai",
    verseRepeat: "Ulang per Ayat",
    searchAyahTab: "Pencarian Ayat (Global)",
    searchSurahTab: "Daftar Surah",
    searching: "Mencari ayat...",
    noResults: "Tidak ada ayat yang cocok.",
    resultsCount: "Ditemukan {count} ayat",
    bookmarkSuccess: "Ditambahkan ke bookmark",
    bookmarkRemoved: "Dihapus dari bookmark",
    noBookmarks: "Belum ada bookmark ayat.",
    lastReadNone: "Belum ada riwayat membaca.",
    openQuran: "Buka Al-Qur'an",
    surahListNav: "Daftar Surah",
    landingHeroTitle: "Temukan Ketenangan Dalam Al-Qur'an",
    landingHeroSubtitle: "Baca, dengarkan murottal, dan tadabbur Al-Qur'an dengan tampilan modern, transliterasi latin, dan fitur lengkap.",
    landingHeroCta: "Mulai Membaca Sekarang",
    landingHeroCtaSub: "Lihat Fitur",
    landingQuoteTitle: "Ayat Pilihan",
    landingQuoteLoading: "Memuat ayat...",
    landingStatsTitle: "Dalam Angka",
    landingStatsSurah: "Surah",
    landingStatsAyat: "Ayat",
    landingStatsLanguages: "Bahasa",
    landingStatsReciters: "Qori",
    landingFeaturesTitle: "Fitur Tersedia",
    landingFeaturesSubtitle: "Semua yang Anda butuhkan untuk membaca Al-Qur'an dengan khusyuk",
    landingComingSoonTitle: "Segera Hadir",
    landingComingSoonSubtitle: "Fitur-fitur baru yang sedang dalam pengembangan aktif",
    landingComingSoonBadge: "Segera",
    landingCtaTitle: "Siap Memulai?",
    landingCtaSubtitle: "Mulai perjalanan membaca Al-Qur'an Anda sekarang juga, gratis selamanya.",
    landingCtaButton: "Buka Al-Qur'an",
    
    // New Translations
    tafsirTab: "Tafsir",
    bacaTab: "Baca Ayat",
    shalatTab: "Jadwal Shalat",
    imsakiyahTab: "Imsakiyah",
    provinsi: "Provinsi",
    kabkota: "Kabupaten/Kota",
    pilihProvinsi: "Pilih Provinsi...",
    pilihKabKota: "Pilih Kabupaten/Kota...",
    shalatHariIni: "Jadwal Shalat Hari Ini",
    shalatBulanIni: "Jadwal Shalat Bulanan",
    imsakiyahBulanIni: "Jadwal Imsakiyah Ramadhan",
    imsak: "Imsak",
    subuh: "Subuh",
    terbit: "Terbit",
    dhuha: "Dhuha",
    dzuhur: "Dzuhur",
    ashar: "Ashar",
    maghrib: "Maghrib",
    isya: "Isya",
    nextPrayerIn: "Shalat berikutnya ({name}) dalam {time}",
    prayerCountdown: "{hours}j {minutes}m {seconds}d",
    tafsir: "Tafsir",
    tafsirSurah: "Tafsir Surat {name}",
    deskripsiSurah: "Deskripsi Surah",
    tafsirSource: "Tafsir oleh Kemenag RI (Kementerian Agama RI)",
    tafsirSingkat: "Tafsir Singkat",
    showTafsirSingkat: "Tampilkan Tafsir Singkat",
    tafsirSourceLabel: "Sumber Tafsir",
    tafsirKemenag: "Kemenag RI (Tafsir Wajiz)",
    tafsirJalalayn: "Tafsir Jalalain",
    tafsirIbnKathir: "Tafsir Ibn Kathir (Ringkasan)",
    shareCardTitle: "Bagikan Kartu Ayat",
    copyImage: "Salin Gambar",
    downloadImage: "Unduh Gambar",
    selectTheme: "Pilih Tema",
    showArabic: "Tampilkan Arab",
    showTranslation: "Tampilkan Terjemahan",
    showLatinLabel: "Tampilkan Latin",
    salinTeks: "Salin Teks",
    bagikanAyat: "Bagikan Ayat",
    shareSuccess: "Berhasil disalin/dibagikan!",
    bacaTafsir: "Lihat Tafsir",
    tutupTafsir: "Tutup Tafsir",
    juzListNav: "Daftar Juz",
    juz: "Juz",
    invalidJuz: "Nomor juz tidak valid.",
    juzOf: "Juz ke-{current} dari {total}",
    autoTheme: "Tema Otomatis (Waktu)",
    autoThemeDesc: "Ganti tema otomatis sesuai jam (18:00 - 06:00 tema gelap)",
    progressTracker: "Progress Tadarus",
    progressTitle: "Tracker Progress Tadarus",
    streakCount: "{streak} Hari",
    streakTitle: "Streak Membaca",
    totalVersesRead: "Total Ayat Dibaca",
    completedSurahs: "Surah Selesai",
    inProgressSurahs: "Surah Sedang Dibaca",
    resetProgress: "Reset Semua Progress",
    resetConfirm: "Apakah Anda yakin ingin menghapus semua data progress membaca dan streak?",
    statusCompleted: "Selesai",
    statusInProgress: "Sedang Dibaca",
    statusUnread: "Belum Dibaca",
    navSurah: "Surah",
    navShalat: "Shalat",
    navDoa: "Doa",
    navCari: "Cari",
    navProgress: "Progress",
    navBookmark: "Bookmark",
    navAsmaulHusna: "Asmaul Husna",
    navDownloads: "Unduhan",
    downloadsTitle: "Pengelola Audio Offline",
    downloadsSubtitle: "Kelola penyimpanan murottal yang telah Anda unduh untuk didengarkan tanpa koneksi internet.",
    downloadsEmpty: "Belum ada audio murottal yang diunduh secara offline.",
    downloadsStorage: "Penyimpanan Offline",
    downloadsClearAll: "Hapus Semua Unduhan",
    downloadsClearAllConfirm: "Apakah Anda yakin ingin menghapus semua file audio offline yang tersimpan?",
    downloadsClearAllSuccess: "Semua file audio offline berhasil dihapus.",
    downloadExploreSurah: "Jelajahi Surah",
    wordHighlight: "Sorotan Kata demi Kata",
    fontArabicStyle: "Gaya Tulisan Arab",
    fontUthmani: "Uthmani (Lokal/Amiri)",
    fontHafs: "Hafs (Madinah/Scheherazade)",
    fontNaskh: "Naskh (Klasik/Noto)",
    fontIndopak: "Indopak (Asia Selatan)",
    mushafMode: "Mode Mushaf",
    exitMushafMode: "Keluar Mode Mushaf",
    mushafModeDesc: "Tampilan baca klasik tanpa terjemahan dan gangguan",
    useDuoReciter: "Mode 2 Qori (Perbandingan)",
    duoReciterDesc: "Putar Qori A lalu Qori B bergantian per ayat",
    reciterBLabel: "Qori Kedua (B)",
    navHafalan: "Hafalan",
    hafalanTitle: "Asisten Hafalan Mandiri",
    hafalanSubtitle: "Metode interaktif flashcard dan tebak kata untuk memudahkan hafalan Al-Qur'an Anda.",
    selectSurahHafalan: "Pilih Surah untuk Dihafal",
    memorizedBadge: "Sudah Hafal",
    modeFlashcard: "Mode Flashcard",
    modeCloze: "Mode Tebak Kata",
    modeFullHide: "Sembunyi Penuh",
    flashcardClickTip: "Klik kartu untuk membalikkan kartu dan melihat arti terjemahan",
    clozeClickTip: "Sebagian kata disembunyikan. Klik kotak kosong untuk memunculkan kata",
    fullHideClickTip: "Seluruh ayat disembunyikan. Klik area ayat untuk menampilkan/menyembunyikan",
    markMemorized: "Tandai Sudah Hafal",
    removeMemorized: "Hapus dari Hafalan",
    hafalanStatsLabel: "Progress Hafalan Surah",
    emptyHafalanList: "Belum ada ayat yang ditandai sebagai dihafal.",
    totalHafalanLabel: "Total Ayat Dihafal",
    downloadAudio: "Unduh Audio",
    downloadingAudio: "Mengunduh... {progress}%",
    downloadCancel: "Batal",
    downloadedOffline: "Tersimpan Offline",
    deleteOfflineConfirm: "Apakah Anda yakin ingin menghapus file audio offline untuk surah ini?",
    deleteOfflineSuccess: "File audio offline berhasil dihapus.",
    downloadSuccess: "Audio berhasil disimpan secara offline!",
  },
  en: {
    appName: "Al-Qur'an Al-Kareem",
    appSub: "Quran Viewer & Murottal",
    surahList: "Surah List",
    searchPlaceholder: "Search surah name, meaning, or number (e.g., 36, Al-Waqi'ah, Resurrection)...",
    clear: "Clear",
    tryAgain: "Try Again",
    failedLoad: "Failed to load Surah list. Please try again in a few moments.",
    notFound: "Surah not found",
    notFoundSub: "Try searching with another keyword or check your spelling.",
    ayat: "Verses",
    meccan: "Meccan",
    medinan: "Medinan",
    settingsTitle: "Reading Settings",
    settingsClose: "Close",
    translation: "Translation",
    reciter: "Reciter / Murottal",
    fontSize: "Font Size",
    fontArabic: "Arabic",
    fontTranslation: "Translation",
    autoScroll: "Murottal Auto-Scroll",
    extras: "Extra Features",
    backToSurahs: "Back to Surah List",
    prevSurah: "Previous Surah",
    nextSurah: "Next Surah",
    loadingDetails: "Failed to load surah details. Please check your internet connection.",
    invalidSurah: "Invalid surah number.",
    errorTitle: "An Error Occurred",
    backToHome: "Back to Home",
    murottal: "Murottal",
    ayahOf: "Verse {current} of {total}",
    playAyah: "Play Verse Audio",
    copyAyah: "Copy Verse & Translation",
    copied: "Copied!",
    speed: "Playback Speed",
    mute: "Mute",
    unmute: "Unmute",
    themeLight: "Light Theme",
    themeSepia: "Sepia Theme",
    themeDark: "Dark Theme",
    copyright: "© {year} Al-Qur'an Al-Kareem. Powered by Next.js & alquran.cloud.",
    sumberApi: "API Source",
    readListenTadabbur: "READ • LISTEN • REFLECT",
    playSurah: "Play Surah",
    pauseSurah: "Pause Surah",
    readingMode: "Reading Mode",
    language: "App Language",
    floatingSettings: "Open Settings",
    prevAyah: "Previous Verse",
    nextAyah: "Next Verse",
    repeatNone: "No Repeat",
    repeatAyah: "Repeat Verse",
    repeatSurah: "Repeat Surah",
    heroTitle: "Discover Peace In Reading The Quran",
    heroSubtitle: "A modern Quran application equipped with multi-language translations, interactive murottal audio, and auto-scroll to ease your recitation.",
    showLatin: "Show Latin (Transliteration)",
    highlightTajweed: "Highlight Tajweed",
    showIsyarat: "Show Sign Language",
    theme: "Reading Theme",
    themeCycle: "Change Theme",
    lastRead: "Last Read",
    bookmarksTitle: "My Bookmarks",
    tahfidzHelper: "Tahfidz & Repeat Settings",
    loopRange: "Repeat Verse Range",
    startAyah: "Start Verse",
    endAyah: "End Verse",
    verseRepeat: "Repeat per Verse",
    searchAyahTab: "Verse Search (Global)",
    searchSurahTab: "Surah List",
    searching: "Searching verses...",
    noResults: "No matching verses found.",
    resultsCount: "Found {count} verses",
    bookmarkSuccess: "Added to bookmarks",
    bookmarkRemoved: "Removed from bookmarks",
    noBookmarks: "No bookmarked verses yet.",
    lastReadNone: "No reading history yet.",
    openQuran: "Open Al-Qur'an",
    surahListNav: "Surah List",
    landingHeroTitle: "Find Peace and Serenity In The Quran",
    landingHeroSubtitle: "Read, listen to murottal, and reflect on the Quran with a beautiful modern interface and complete features.",
    landingHeroCta: "Start Reading Now",
    landingHeroCtaSub: "See Features",
    landingQuoteTitle: "Featured Verse",
    landingQuoteLoading: "Loading verse...",
    landingStatsTitle: "By The Numbers",
    landingStatsSurah: "Surahs",
    landingStatsAyat: "Verses",
    landingStatsLanguages: "Languages",
    landingStatsReciters: "Reciters",
    landingFeaturesTitle: "Available Features",
    landingFeaturesSubtitle: "Everything you need to read the Quran with focus and serenity",
    landingComingSoonTitle: "Coming Soon",
    landingComingSoonSubtitle: "New features currently in active development",
    landingComingSoonBadge: "Soon",
    landingCtaTitle: "Ready to Begin?",
    landingCtaSubtitle: "Start your Quran reading journey right now, forever free.",
    landingCtaButton: "Open Al-Qur'an",

    // New Translations (EN)
    tafsirTab: "Tafsir",
    bacaTab: "Read Verses",
    shalatTab: "Prayer Times",
    imsakiyahTab: "Imsakiyah",
    provinsi: "Province",
    kabkota: "Regency/City",
    pilihProvinsi: "Select Province...",
    pilihKabKota: "Select Regency/City...",
    shalatHariIni: "Today's Prayer Schedule",
    shalatBulanIni: "Monthly Prayer Schedule",
    imsakiyahBulanIni: "Ramadhan Imsakiyah Schedule",
    imsak: "Imsak",
    subuh: "Fajr",
    terbit: "Sunrise",
    dhuha: "Dhuha",
    dzuhur: "Dhuhr",
    ashar: "Asr",
    maghrib: "Maghrib",
    isya: "Isha",
    nextPrayerIn: "Next prayer ({name}) in {time}",
    prayerCountdown: "{hours}h {minutes}m {seconds}s",
    tafsir: "Tafsir",
    tafsirSurah: "Tafsir of Surah {name}",
    deskripsiSurah: "Surah Description",
    tafsirSource: "Tafsir by Kemenag RI (Ministry of Religious Affairs of Indonesia)",
    tafsirSingkat: "Brief Tafsir",
    showTafsirSingkat: "Show Brief Tafsir",
    tafsirSourceLabel: "Tafsir Source",
    tafsirKemenag: "Kemenag RI (Indonesian)",
    tafsirJalalayn: "Tafsir Jalalain (Indonesian)",
    tafsirIbnKathir: "Tafsir Ibn Kathir (English)",
    shareCardTitle: "Share Ayah Card",
    copyImage: "Copy Image",
    downloadImage: "Download Image",
    selectTheme: "Select Theme",
    showArabic: "Show Arabic",
    showTranslation: "Show Translation",
    showLatinLabel: "Show Transliteration",
    salinTeks: "Copy Text",
    bagikanAyat: "Share Ayah",
    shareSuccess: "Successfully copied/shared!",
    bacaTafsir: "Read Tafsir",
    tutupTafsir: "Close Tafsir",
    juzListNav: "Juz List",
    juz: "Juz",
    invalidJuz: "Invalid juz number.",
    juzOf: "Juz {current} of {total}",
    autoTheme: "Auto Theme (Time)",
    autoThemeDesc: "Switch theme automatically based on time (6 PM - 6 AM dark theme)",
    progressTracker: "Tadarus Progress",
    progressTitle: "Tadarus Progress Tracker",
    streakCount: "{streak} Days",
    streakTitle: "Reading Streak",
    totalVersesRead: "Total Verses Read",
    completedSurahs: "Completed Surahs",
    inProgressSurahs: "In Progress Surahs",
    resetProgress: "Reset All Progress",
    resetConfirm: "Are you sure you want to reset all reading progress and streak data?",
    statusCompleted: "Completed",
    statusInProgress: "In Progress",
    statusUnread: "Unread",
    navSurah: "Surah",
    navShalat: "Prayer",
    navDoa: "Du'a",
    navCari: "Search",
    navProgress: "Progress",
    navBookmark: "Bookmarks",
    navAsmaulHusna: "Asmaul Husna",
    navDownloads: "Downloads",
    downloadsTitle: "Offline Audio Manager",
    downloadsSubtitle: "Manage murottal audio storage that you have downloaded to listen offline without internet.",
    downloadsEmpty: "No murottal audio has been downloaded offline yet.",
    downloadsStorage: "Offline Storage",
    downloadsClearAll: "Clear All Downloads",
    downloadsClearAllConfirm: "Are you sure you want to delete all cached offline audio files?",
    downloadsClearAllSuccess: "All offline audio files cleared successfully.",
    downloadExploreSurah: "Explore Surah",
    wordHighlight: "Word-by-Word Highlight",
    fontArabicStyle: "Arabic Font Style",
    fontUthmani: "Uthmani (Amiri)",
    fontHafs: "Hafs (Scheherazade)",
    fontNaskh: "Naskh (Classic/Noto)",
    fontIndopak: "Indopak (South Asian)",
    mushafMode: "Mushaf Mode",
    exitMushafMode: "Exit Mushaf Mode",
    mushafModeDesc: "Classic reading view without translations and distractions",
    useDuoReciter: "Duo Reciter Mode (Comparison)",
    duoReciterDesc: "Play Reciter A then Reciter B sequentially per verse",
    reciterBLabel: "Second Reciter (B)",
    navHafalan: "Memorize",
    hafalanTitle: "Quran Memorization Helper",
    hafalanSubtitle: "Interactive flashcard and cloze test methods to help you memorize the Quran easily.",
    selectSurahHafalan: "Select Surah to Memorize",
    memorizedBadge: "Memorized",
    modeFlashcard: "Flashcard Mode",
    modeCloze: "Cloze Test Mode",
    modeFullHide: "Full Hide Mode",
    flashcardClickTip: "Click card to flip and view the translation",
    clozeClickTip: "Some words are hidden. Click the empty box to reveal the word",
    fullHideClickTip: "The entire verse is hidden. Click the verse area to show/hide",
    markMemorized: "Mark as Memorized",
    removeMemorized: "Remove from Memorized",
    hafalanStatsLabel: "Surah Memorization Progress",
    emptyHafalanList: "No verses marked as memorized yet.",
    totalHafalanLabel: "Total Verses Memorized",
    downloadAudio: "Download Audio",
    downloadingAudio: "Downloading... {progress}%",
    downloadCancel: "Cancel",
    downloadedOffline: "Saved Offline",
    deleteOfflineConfirm: "Are you sure you want to delete the offline audio files for this surah?",
    deleteOfflineSuccess: "Offline audio files deleted successfully.",
    downloadSuccess: "Audio saved offline successfully!",
  }
};

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: keyof typeof UI_TRANSLATIONS.id, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageType>("id");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const storedLang = localStorage.getItem("quran-lang") as LanguageType || "id";
    setLanguageState(storedLang);
    setMounted(true);
  }, []);

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem("quran-lang", lang);
  };

  const t = (key: keyof typeof UI_TRANSLATIONS.id, params?: Record<string, string | number>): string => {
    let text = UI_TRANSLATIONS[language][key] || UI_TRANSLATIONS["id"][key] || String(key);
    
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
